---
- name: Install etckeeper
  package:
    name: etckeeper
    state: present
  register: etckeeper_install

- name: Initalize etckeeper
  command: etckeeper init
  when: etckeeper_install is succeeded
