---
- name: Enable Powertools
  command: dnf config-manager --set-enabled powertools

- name: Enable Fedora Copr for Wireguard
  command:
    cmd: dnf copr enable -y jdoss/wireguard
    creates: /etc/yum.repos.d/_copr_jdoss-wireguard.repo

- name: Install DKMS
  package:
    name: dkms
    state: present

- name: Install Wireguard DKMS
  package:
    name: wireguard-dkms
    state: present

- name: Install Wireguard Tools
  package:
    name: wireguard-tools
    state: present

- name: Copy /etc/modules-load.d/wireguard.conf
  copy:
    src: files/modules-load-wireguard.conf
    dest: /etc/modules-load.d/wireguard.conf
