---
- name: Install Yubico Key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 32CBA1A9
  when: ansible_distribution == 'Ubuntu'
  register: ubuntu_install_key

- name: Install Yubico Repository (Ubuntu)
  apt_repository:
    repo: ppa:yubico/stable
    state: present
    update_cache: yes
  when: ansible_distribution == 'Ubuntu' and ubuntu_install_key is succeeded
  register: ubuntu_install_repo

- name: Install Yubico (Ubuntu)
  package:
    name: "{{item}}"
    state: latest
  register: ubuntu_install_yubico
  with_items:
    - yubikey-manager-qt
    - yubikey-personalization-gui
    - yubikey-personalization
    - qrencode
    - caca-utils
  when: ansible_distribution == 'Ubuntu' and ubuntu_install_repo is succeeded
#    - yubioath-desktop
