---
- name: Install Tilix
  become: yes
  package:
    name: tilix
    state: present

- name: Make Tilix default for <ctrl>+<alt>+t
  alternatives:
    name: x-terminal-emulator
    path: /usr/bin/tilix.wrapper

