- name: Install Docker Repo (Fedora)
  yum_repository:
    name: Docker
    description: Docker repo
    baseurl: https://download.docker.com/linux/fedora/$releasever/$basearch/stable
    gpgkey: https://download.docker.com/linux/fedora/gpg
  when: ansible_distribution == 'Fedora'
  register: fedora_install

- name: Install docker
  package:
    name: "{{item}}"
    state: present
  when: fedora_install is succeeded
  register: install_packages
  with_items:
    - docker-ce
    - containerd.io
    - docker-ce-cli

- name: Copy daemon.json to /etc/docker/
  copy:
    src: files/daemon.json
    dest: /etc/docker/daemon.json
  register: daemon_json_installed
  when: install_packages is succeeded

- name: mkdir /etc/systemd/system/docker.service.d
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
  
- name: Restart docker service
  systemd:
    name: docker
    state: restarted
    enabled: yes
    daemon_reload: yes
  when: daemon_json_installed is succeeded
