- name: Remove Podman
  package:
    name: "{{item}}"
    state: absent
  register: podman_removed
  with_items:
    - podman
    - podman-docker
    - podman-manpages
    - buildah
    - runc

- name: Install Docker Repo (Fedora)
  yum_repository:
    name: Docker
    description: Docker repo
    baseurl: https://download.docker.com/linux/fedora/$releasever/$basearch/stable
    gpgkey: https://download.docker.com/linux/fedora/gpg
  when: ansible_distribution == 'Fedora'
  register: fedora_install

- name: Install Docker Repo (CentOS)
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo
  when: ansible_distribution == 'CentOS'
  register: centos_install

- name: Install containerd
  yum:
    name: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm
  when: ansible_distribution == 'CentOS' and centos_install is succeeded
  register: containerd_install
  
- name: Install docker
  package:
    name: "{{item}}"
    state: present
  when: (fedora_install is succeeded or centos_install is succeeded) and podman_removed is succeeded
  register: install_packages
  with_items:
    - docker-ce
    - containerd.io
    - docker-ce-cli

- name: Copy daemon.json to /etc/docker/
  copy:
    src: files/daemon.json
    dest: /etc/docker/daemon.json
  register: daemon_json_installed
  when: install_packages is succeeded and ansible_distribution == 'Fedora'

- name: mkdir /etc/systemd/system/docker.service.d
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
  when: ansible_distribution == 'Fedora'

- name: Restart docker service
  systemd:
    name: docker
    state: restarted
    enabled: yes
    daemon_reload: yes
  when: daemon_json_installed is succeeded or (centos_install is succeeded and install_packages is succeeded)
