- name: Install git
  become: yes
  package:
    name: git
    state: present

- name: Install gitconfig
  copy:
    src: "files/gitconfig"
    dest: "{{HOME}}/.gitconfig"
    owner: "{{USER}}"
    group: "{{USER}}"
    mode: '600'
