- hosts: 'beast'
  remote_user: root
  roles:
    - role: ../roles/common/etckeeper
    - role: ../roles/desktop/terminal
    - role: ../roles/desktop/developer
    - role: ../roles/server/virtualization-host
  vars:
    USER: rwlove
    HOME: /home/rwlove
