- hosts: 127.0.0.1
  connection: local
  roles:
    - role: ../roles/common/etckeeper    
    - role: ../roles/media
    - role: ../roles/desktop/terminal
    - role: ../roles/desktop/developer
    - role: ../roles/desktop/authentication
    - role: ../roles/work/redhat

  vars:
    USER: rwlove
    KODI_CONFIG_DIR: /home/rwlove/.kodi
    HOME: /home/rwlove
