- hosts:
    - worker2
    - worker3
    - worker4
    - worker5
    - worker6
    - worker7
  roles:
    - role: roles/common/redhat/epel
    - role: kubernetes/network/wireguard
    - role: kubernetes/network/tc
    - role: common/nfs
    - role: common/etckeeper
    - role: server/network-tools
    - role: desktop/developer
    - role: desktop/terminal
    - role: kubernetes/worker
#    - role: ../roles/kubernetes/network/ovn-kubernetes

  vars:
    USER: root
    HOME: /root
    roles_path: ../roles

#    - worker1
#    - worker2
#    - worker3
#    - worker4
