- hosts:
    - worker4
  roles:
    - role: common/nfs
    - role: common/etckeeper
    - role: server/network-tools
    - role: desktop/developer
    - role: desktop/terminal
    - role: kubernetes/worker
#    - role: ../roles/kubernetes/network/ovn-kubernetes

  vars:
    USER: root
    HOME: /root
    roles_path: ../roles

#    - worker1
#    - worker2
#    - worker3
